/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCarrinhoRouteImport } from './routes/_authenticated/carrinho'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedPedidoRevisarRouteImport } from './routes/_authenticated/pedido.revisar'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedPedidosOrderIdRouteImport } from './routes/_authenticated/pedidos.$orderId'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarrinhoRoute = AuthenticatedCarrinhoRouteImport.update({
  id: '/_authenticated/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/_authenticated/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/_authenticated/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPedidoRevisarRoute =
  AuthenticatedPedidoRevisarRouteImport.update({
    id: '/_authenticated/pedido/revisar',
    path: '/pedido/revisar',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/_authenticated/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPedidosOrderIdRoute =
  AuthenticatedPedidosOrderIdRouteImport.update({
    id: '/_authenticated/pedidos/$orderId',
    path: '/pedidos/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/': typeof AuthenticatedIndexRoute
  '/pedido/revisar': typeof AuthenticatedPedidoRevisarRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/': typeof AuthenticatedIndexRoute
  '/pedido/revisar': typeof AuthenticatedPedidoRevisarRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/carrinho': typeof AuthenticatedCarrinhoRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pedido/revisar': typeof AuthenticatedPedidoRevisarRoute
  '/_authenticated/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/carrinho'
    | '/carteira'
    | '/catalogo'
    | '/'
    | '/pedido/revisar'
    | '/pedidos/$orderId'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/carrinho'
    | '/carteira'
    | '/catalogo'
    | '/'
    | '/pedido/revisar'
    | '/pedidos/$orderId'
    | '/pedidos'
  id:
    | '__root__'
    | '/_authenticated/carrinho'
    | '/_authenticated/carteira'
    | '/_authenticated/catalogo'
    | '/_authenticated/'
    | '/_authenticated/pedido/revisar'
    | '/_authenticated/pedidos/$orderId'
    | '/_authenticated/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedCarrinhoRoute: typeof AuthenticatedCarrinhoRoute
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPedidoRevisarRoute: typeof AuthenticatedPedidoRevisarRoute
  AuthenticatedPedidosOrderIdRoute: typeof AuthenticatedPedidosOrderIdRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carrinho': {
      id: '/_authenticated/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AuthenticatedCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedido/revisar': {
      id: '/_authenticated/pedido/revisar'
      path: '/pedido/revisar'
      fullPath: '/pedido/revisar'
      preLoaderRoute: typeof AuthenticatedPedidoRevisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedidos/$orderId': {
      id: '/_authenticated/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof AuthenticatedPedidosOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedCarrinhoRoute: AuthenticatedCarrinhoRoute,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPedidoRevisarRoute: AuthenticatedPedidoRevisarRoute,
  AuthenticatedPedidosOrderIdRoute: AuthenticatedPedidosOrderIdRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
